image: debian:buster-slim

before_script:
  - apt-get install ca-certificates gnupg curl && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 && echo "deb https://cran.rstudio.com/bin/linux/ubuntu trusty/" | tee -a /etc/apt/sources.list
  - apt-get update -y && apt-get install -y make bundler r-base
  - Rscript -e "install.packages('knitr', repos = 'https://', dependencies = TRUE)"
  - Rscript -e "install.packages('stringr', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  - Rscript -e "install.packages('checkpoint', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  - Rscript -e "install.packages('ggplot2', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  - bundle install

pages:
  stage: deploy
  script:
  - mkdir _episodes && make site && mv _site public
  artifacts:
    paths:
    - public
  only:
  - master
